### PR TITLE
fix integration test

### PR DESCRIPTION
**Pull request by richrines1**
* update requirements to reflect that we currently don't support circuits submitted via `qiskit-terra>=0.19.0` (part of `qiskit>=0.33.0`)
* update gateset used in expected circuits

### CODE REVIEW

**Review by singular-value — APPROVED** [review]
Would this mean we're kicking the can on figuring out what to do about server-client mismatch for qpy?

(fair enough, 🐆 )

**Comment by richrines1** [comment]
> Would this mean we're kicking the can on figuring out what to do about server-client mismatch for qpy?

I guess I was thinking of it more as "making everything work in the meantime" - the mismatch issue is definitely something we need to figure out, but limiting the qiskit version should at least make sure qiskit-superstaq calls continue to function correctly as we do

**Comment by singular-value** [comment]
Sounds good

**Review by vtomole — APPROVED** [review]
👍  On having this as a temp fix.

**Pull request merged**
