### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by paaige**
#129

### CODE REVIEW

**Review by vtomole — APPROVED** [review]
Oh is this really it? Thought more changes would be needed. I trust you tested this locally. LGTM

**Comment by paaige** [comment]
> Oh is this really it? Thought more changes would be needed. I trust you tested this locally. LGTM

Yeah, connecting to superstaq works but there's a hang when I run the job (unless the request is really this slow?). So I'm going to hold off on merging until I'm sure the test works as it did previously.

**Comment by vtomole** [comment]
Worked for me.

**Comment by singular-value** [comment]
Thanks!

**Pull request merged**
