### PR TITLE
use "target" instead of "backend" in api calls

### PR DESCRIPTION
**Pull request by richrines1**
attempts to make consistent use of
* `target` when referring to a superstaq-formatted target string (e.g. "ibmq_lima_qpu")
* `backend` when referring to actual Backend objects (i.e. instances of `qiskit.providers.Backend`, including `SuperstaQBackend`s)

assumes https://github.com/SupertechLabs/general-superstaq/pull/146 and https://github.com/SupertechLabs/general-superstaq/pull/147 (i've confirmed tests pass locally once both are merged)

### CODE REVIEW

**Comment by dowusu-antwi** [comment]
@singular-value I can take this (I'm reviewing the server-side changes)

**Review by dowusu-antwi — DISMISSED** [review]
lgtm

(tests passed for me as well after `pip install -e .`-ing a local merge of https://github.com/SupertechLabs/general-superstaq/pull/146/files and https://github.com/SupertechLabs/general-superstaq/pull/147)

**Comment by singular-value** [comment]
Thanks David.

**Review by vtomole — APPROVED** [review]
LGTM

**Pull request merged**
