### PR TITLE
Get AQT configs in `aqt_compile.ipynb`

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Review by richrines1 — DISMISSED** [review]
lgtm

**Review by richrines1 — APPROVED** [review]
lgtm

**Comment by vtomole** [comment]
Thanks. Will merge after final testing on latest deploy of SuperstaQ that is currently ongoing.

**Comment by vtomole** [comment]
Tested on latest deploy of SuperstaQ.

**Pull request merged**
