### PR TITLE
Change qss endianess to match qiskit

### LINKED ISSUE #174: `qss` doesn't obey `qiskit`s endianess
Qiskit users would be surprised by the following:

```python
import qiskit
import qiskit_superstaq as qss

circ = qiskit.QuantumCircuit(2)
circ.x(0)
circ.measure_all()

superstaq = qss.superstaq_provider.SuperstaQProvider(token)
simulator = qiskit.Aer.get_backend('aer_simulator')
qiskit_result = simulator.run(circ, shots=10).result()
backend = superstaq.get_backend("ibmq_qasm_simulator")
qss_result = backend.run(circ, shots=10).result()

print(qiskit_result.get_counts()) # {'01': 10}
print(qss_result.get_counts()) # {'10': 10}
```

### PR DESCRIPTION
**Pull request by pgoiporia**
Closes #174

### CODE REVIEW

**Comment by pgoiporia** [comment]
@vtomole have a mypy issue here that I'm not sure how to fix.

**Comment by vtomole** [comment]
The return type for `wait_for_results` might be too lenient. Do things still work (Submission of jobs and getting the counts) if we update it to 

```python
    def _wait_for_results(
        self, timeout: Optional[float] = None, wait: float = 5
    ) -> List[Dict[str, Dict[str, int]]]:

        result_list: List[Dict[str, Dict[str, int]]] = []
```

**Comment by pgoiporia** [comment]
> The return type for `wait_for_results` might be too lenient. Do things still work (Submission of jobs and getting the counts) if we update it to
> 
> ```python
>     def _wait_for_results(
>         self, timeout: Optional[float] = None, wait: float = 5
>     ) -> List[Dict[str, Dict[str, int]]]:
> 
>         result_list: List[Dict[str, Dict[str, int]]] = []
> ```

This worked! Thanks!

**Review by perlinm — APPROVED** [review]
lgtm

**Pull request merged**
