### PR TITLE
`encode_file` implementation

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Comment by pgoiporia** [comment]
I think you somehow added commits that have already been pushed @vtomole

**Comment by vtomole** [comment]
@pgoiporia Reverted

**Review by pgoiporia — APPROVED** [review]
LGTM. Nice! I'm a bit confused though. In the pr description you said you were moving this to gss. Shouldn't this just be in css and qss?

**Comment by vtomole** [comment]
@pgoiporia The PR description is outdated. I've updated it.

**Pull request merged**
