### PR TITLE
Fix integration test

### PR DESCRIPTION
**Pull request by singular-value**
Cousin to https://github.com/SupertechLabs/cirq-superstaq/pull/448

I think this will close https://github.com/SupertechLabs/qiskit-superstaq/issues/304.

### CODE REVIEW

**Review by richrines1 — APPROVED** [review]
lgtm! though is there any way to make these tests less brittle?

**Comment by vtomole** [comment]
We deliberately made these tests brittle so we could be reminded when IBM's calibrations changed. I don't know how useful this has been though so i'll defer to @singular-value  and @dowusu-antwi.

**Comment by dowusu-antwi** [comment]
> We deliberately made these tests brittle so we could be reminded when IBM's calibrations changed. I don't know how useful this has been though so i'll defer to @singular-value and @dowusu-antwi for an answer.

It's nice to know when the calibrations change, but if it's too often we should redesign these tests (on account of using the less brittle `RZXCalibration` now instead of relying on `CX` calibration like we used to).

**Comment by vtomole** [comment]
Maybe test failures are not a good way to signal configuration changes if said changes won't break SuperstaQ.

Another option is having our Teams bot post on #superstaq when this happens. Good for long term; maybe for onboarding or intern but i think we should turn them off here because i'm assuming updating these regularly is annoying for the people who do it.

**Review by hallben4 — APPROVED** [review]
Ditto comment on cousin request. Lgtm

**Comment by singular-value** [comment]
Right, this isn't the 100% ideal way to alert of changes, but it doesn't happen very frequently (2x or 3x in past six months I think).

**Review by hallben4 — APPROVED** [review]
lgtm

**Comment by vtomole** [comment]
@singular-value You'll need to move this PR to https://github.com/SupertechLabs/superstaq-server

**Pull request merged**
