### PR TITLE
Finance and logistic methods in `SuperstaQProvider`

### PR DESCRIPTION
**Pull request by vtomole**
Fixes: https://github.com/SupertechLabs/qiskit-superstaq/issues/52

### CODE REVIEW

**Comment by vtomole** [comment]
@richrines1 @dowusu-antwi Ready for review.

**Review by richrines1 — COMMENTED** [review]
couldn't `SuperstaQProvider` just inherit from `Finance` and `Logistics`?

**Comment by vtomole** [comment]
> couldn't SuperstaQProvider just inherit from Finance and Logistics?

Ooo very nice! Done.

**Review by richrines1 — APPROVED** [review]
awesome, lgtm!

**Pull request merged**
